### ISSUE TITLE
Scanning files in Windows desktop folder can be slow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/e2u#6]
```
Navigate to the user home on Windows. Note how much time it takes.


```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 24 Sep 2012 at 8:54

**Comment by joeha480** [comment]
May not be relevant anymore since the file scanning has been rewritten. If this is still an issue, create an updated issue in Dotify Studio.
